---
language: node_js

node_js:
  - 0.10

branches:
  except:
  - gh-pages

env:
  matrix:
    - TEST=unit
    - TEST=sauce
  global:
    - secure: "GhqCBThsPRyVORGZwqvW8jdBza2qc7zgYF2rRaksTQzAYLvrX+UXuoAZSbkF\nWAmd4Dx3IfUm5Hv/NKg41Snh1XNsJrU2aXh5VZEbi9xCs5pwQ87zSXOvDjEr\nwTqfLISlyrUBNSIYjcUEE029jBCKq63giK4QVeL58FY9AKC2MxQ="
    - secure: "gtSV2z58U4UJ8gzvPgPaA8+91ySrqEkcAgfhtTHEt+ayGAIZibeVi+RRSaGW\nTY3Vaonn8jfT9L7f49v4UHtsUO9fY5W4Q/kkXyrifTBfbcAlnIcVPZvvZBck\njcFwW4MqO4WwqgdR1+Yo8gQQq0tOj5lVSAEI+tJhPZQB7BdiX3M="

before_script:
  - if [ "x$TEST" == "xsauce" ]; then curl -L https://gist.githubusercontent.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash; fi
  - npm install -g gulp

script:
  - '[ "${TEST}" = "sauce" -a "${TRAVIS_PULL_REQUEST}" != "false"] && true || gulp --require LiveScript test:$TEST'

before_deploy: "BUILD=git-`git describe --always` gulp --require LiveScript build ly-diff server --env production"

deploy:
  on:
    branch: master
    condition: "$TEST = unit"
  provider: nodejitsu
  user: clkao
  skip_cleanup: true
  api_key:
    secure: ! 'ZTIUonMOmBRMz5SpI0GvkBLAjoZuq6M4b7flq7HFDAQoaxv6Gok3UOMGmUV6

      mI7uGnLqAggYjWeoIF6yFUIN69hLpIwvfZylOdPU+h/W+H0xlxxtHCvSyc5R

      Ad1AHf93zbf845Cg4LSR0I6fKPewhBW8uFKF5ZYcd7ppofwYrI8='

notifications:
  irc:
    channels:
      - "irc.freenode.net#g0v.tw"
    on_success: always
